// <auto-generated />
using System;
using CcsSso.DbPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CcsSso.DbMigrations.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CcsSso.DbModel.Entity.CcsAccessRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CcsAccessRoleDescription")
                        .HasColumnType("text");

                    b.Property<string>("CcsAccessRoleName")
                        .HasColumnType("text");

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CcsAccessRole");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ContactDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ContactDetail");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ContactPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("ContactDetailId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactPointReasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<int>("PartyTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailId");

                    b.HasIndex("ContactPointReasonId");

                    b.HasIndex("PartyId");

                    b.HasIndex("PartyTypeId");

                    b.ToTable("ContactPoint");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ContactPointReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactPointReason");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.EnterpriseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("EnterpriseTypeName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EnterpriseType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.IdentityProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("ExternalIdpFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("IdpName")
                        .HasColumnType("text");

                    b.Property<string>("IdpUri")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IdentityProvider");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CiiOrganisationId")
                        .HasColumnType("text");

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("LegalName")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationUri")
                        .HasColumnType("text");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("RightToBuy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CiiOrganisationId");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.OrganisationAccessRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("OrganisationAccessRoleDescription")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationAccessRoleName")
                        .HasColumnType("text");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("OrganisationAccessRole");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.OrganisationEnterpriseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("EnterpriseTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseTypeId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("OrganisationEnterpriseType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("PartyTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartyTypeId");

                    b.ToTable("Party");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.PartyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("PartyTypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PartyType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<int>("Title")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.PhysicalAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("ContactDetailId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("Locality")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<string>("Uprn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailId")
                        .IsUnique();

                    b.ToTable("PhysicalAddress");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ProcurementGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("ProcurementGroup");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.TradingOrganisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.Property<string>("TradingName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("TradingOrganisation");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("IdentityProviderId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("UserTitle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdentityProviderId");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserAccessRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("CcsAccessRoleId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganisationAccessRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CcsAccessRoleId");

                    b.HasIndex("OrganisationAccessRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccessRole");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserGroupName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserGroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MembershipEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupMembership");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserSettingTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("UserSettingValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSettingTypeId");

                    b.ToTable("UserSetting");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserSettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserSettingName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSettingType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.VirtualAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("ContactDetailId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("VirtualAddressTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("VirtualAddressValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailId");

                    b.HasIndex("VirtualAddressTypeId");

                    b.ToTable("VirtualAddress");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.VirtualAddressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("ConcurrencyKey")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastUpdatedPartyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VirtualAddressType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ContactPoint", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.ContactDetail", "ContactDetail")
                        .WithMany("ContactPoints")
                        .HasForeignKey("ContactDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.ContactPointReason", "ContactPointReason")
                        .WithMany("ContactPoints")
                        .HasForeignKey("ContactPointReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.Party", "Party")
                        .WithMany("ContactPoints")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.PartyType", "PartyType")
                        .WithMany()
                        .HasForeignKey("PartyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");

                    b.Navigation("ContactPointReason");

                    b.Navigation("Party");

                    b.Navigation("PartyType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Organisation", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.Party", "Party")
                        .WithOne("Organisation")
                        .HasForeignKey("CcsSso.DbModel.Entity.Organisation", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.OrganisationAccessRole", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.Organisation", "Organisation")
                        .WithMany("OrganisationAccessRoles")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.OrganisationEnterpriseType", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.EnterpriseType", "EnterpriseType")
                        .WithMany("OrganisationEnterpriseTypes")
                        .HasForeignKey("EnterpriseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.Organisation", "Organisation")
                        .WithMany("OrganisationEnterpriseTypes")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnterpriseType");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Party", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.PartyType", "PartyType")
                        .WithMany("Party")
                        .HasForeignKey("PartyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Person", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.Organisation", "Organisation")
                        .WithMany("People")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.Party", "Party")
                        .WithOne("Person")
                        .HasForeignKey("CcsSso.DbModel.Entity.Person", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.PhysicalAddress", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.ContactDetail", "ContactDetail")
                        .WithOne("PhysicalAddress")
                        .HasForeignKey("CcsSso.DbModel.Entity.PhysicalAddress", "ContactDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ProcurementGroup", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.TradingOrganisation", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.Organisation", "Organisation")
                        .WithMany("TradingOrganisations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.User", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.IdentityProvider", "IdentityProvider")
                        .WithMany("Users")
                        .HasForeignKey("IdentityProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.Party", "Party")
                        .WithOne("User")
                        .HasForeignKey("CcsSso.DbModel.Entity.User", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityProvider");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserAccessRole", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.CcsAccessRole", "CcsAccessRole")
                        .WithMany("UserAccessRoles")
                        .HasForeignKey("CcsAccessRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.OrganisationAccessRole", "OrganisationAccessRole")
                        .WithMany("UserAccessRoles")
                        .HasForeignKey("OrganisationAccessRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.User", "User")
                        .WithMany("UserAccessRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CcsAccessRole");

                    b.Navigation("OrganisationAccessRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserGroup", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.Organisation", "Organisation")
                        .WithMany("UserGroups")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserGroupMembership", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.UserGroup", "UserGroup")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.User", "User")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserSetting", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.User", "User")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.UserSettingType", "UserSettingType")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserSettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserSettingType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.VirtualAddress", b =>
                {
                    b.HasOne("CcsSso.DbModel.Entity.ContactDetail", "ContactDetail")
                        .WithMany("VirtualAddresses")
                        .HasForeignKey("ContactDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcsSso.DbModel.Entity.VirtualAddressType", "VirtualAddressType")
                        .WithMany("VirtualAddresses")
                        .HasForeignKey("VirtualAddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");

                    b.Navigation("VirtualAddressType");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.CcsAccessRole", b =>
                {
                    b.Navigation("UserAccessRoles");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ContactDetail", b =>
                {
                    b.Navigation("ContactPoints");

                    b.Navigation("PhysicalAddress");

                    b.Navigation("VirtualAddresses");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.ContactPointReason", b =>
                {
                    b.Navigation("ContactPoints");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.EnterpriseType", b =>
                {
                    b.Navigation("OrganisationEnterpriseTypes");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.IdentityProvider", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Organisation", b =>
                {
                    b.Navigation("OrganisationAccessRoles");

                    b.Navigation("OrganisationEnterpriseTypes");

                    b.Navigation("People");

                    b.Navigation("TradingOrganisations");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.OrganisationAccessRole", b =>
                {
                    b.Navigation("UserAccessRoles");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.Party", b =>
                {
                    b.Navigation("ContactPoints");

                    b.Navigation("Organisation");

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.PartyType", b =>
                {
                    b.Navigation("Party");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.User", b =>
                {
                    b.Navigation("UserAccessRoles");

                    b.Navigation("UserGroupMemberships");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserGroup", b =>
                {
                    b.Navigation("UserGroupMemberships");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.UserSettingType", b =>
                {
                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("CcsSso.DbModel.Entity.VirtualAddressType", b =>
                {
                    b.Navigation("VirtualAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
