CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "CcsAccessRole" (
    "CcsAccessRoleId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CcsAccessRoleName" text NULL,
    "CcsAccessRoleDescription" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_CcsAccessRole" PRIMARY KEY ("CcsAccessRoleId")
);

CREATE TABLE "EnterpriseType" (
    "EnterpriseTypeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EnterpriseTypeName" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_EnterpriseType" PRIMARY KEY ("EnterpriseTypeId")
);

CREATE TABLE "IdentityProvider" (
    "IdpId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdpUri" text NULL,
    "IdpName" text NULL,
    "ExternalIdpFlag" boolean NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_IdentityProvider" PRIMARY KEY ("IdpId")
);

CREATE TABLE "PartyType" (
    "PartyTypeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PartyTypeName" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_PartyType" PRIMARY KEY ("PartyTypeId")
);

CREATE TABLE "UserSettingType" (
    "UserSettingTypeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserSettingName" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserSettingType" PRIMARY KEY ("UserSettingTypeId")
);

CREATE TABLE "VirtualAddressType" (
    "VirtualAddressTypeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_VirtualAddressType" PRIMARY KEY ("VirtualAddressTypeId")
);

CREATE TABLE "Party" (
    "PartyId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PartyTypeId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_Party" PRIMARY KEY ("PartyId"),
    CONSTRAINT "FK_Party_PartyType_PartyTypeId" FOREIGN KEY ("PartyTypeId") REFERENCES "PartyType" ("PartyTypeId") ON DELETE CASCADE
);

CREATE TABLE "ContactPoint" (
    "ContactPointId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PartyId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ContactPoint" PRIMARY KEY ("ContactPointId"),
    CONSTRAINT "FK_ContactPoint_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("PartyId") ON DELETE CASCADE
);

CREATE TABLE "Organisation" (
    "OrganisationId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationUri" text NULL,
    "RightToBuy" boolean NOT NULL,
    "PartyId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_Organisation" PRIMARY KEY ("OrganisationId"),
    CONSTRAINT "FK_Organisation_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("PartyId") ON DELETE CASCADE
);

CREATE TABLE "User" (
    "UserId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NULL,
    "SurName" text NULL,
    "JobTitle" text NULL,
    "UserTitle" integer NOT NULL,
    "PartyId" integer NOT NULL,
    "IdentityProviderIdpId" integer NULL,
    "IdpId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_User_IdentityProvider_IdentityProviderIdpId" FOREIGN KEY ("IdentityProviderIdpId") REFERENCES "IdentityProvider" ("IdpId") ON DELETE RESTRICT,
    CONSTRAINT "FK_User_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("PartyId") ON DELETE CASCADE
);

CREATE TABLE "ContactDetail" (
    "ContactDetailId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ContactPointId" integer NOT NULL,
    "EffectiveFrom" timestamp without time zone NOT NULL,
    "EffectiveTo" timestamp without time zone NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ContactDetail" PRIMARY KEY ("ContactDetailId"),
    CONSTRAINT "FK_ContactDetail_ContactPoint_ContactPointId" FOREIGN KEY ("ContactPointId") REFERENCES "ContactPoint" ("ContactPointId") ON DELETE CASCADE
);

CREATE TABLE "OrganisationAccessRole" (
    "OrganisationAccessRoleId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "OrganisationAccessRoleName" text NULL,
    "OrganisationAccessRoleDescription" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationAccessRole" PRIMARY KEY ("OrganisationAccessRoleId"),
    CONSTRAINT "FK_OrganisationAccessRole_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("OrganisationId") ON DELETE CASCADE
);

CREATE TABLE "OrganisationEnterpriseType" (
    "OrganisationEnterpriseTypeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "EnterpriseTypeId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationEnterpriseType" PRIMARY KEY ("OrganisationEnterpriseTypeId"),
    CONSTRAINT "FK_OrganisationEnterpriseType_EnterpriseType_EnterpriseTypeId" FOREIGN KEY ("EnterpriseTypeId") REFERENCES "EnterpriseType" ("EnterpriseTypeId") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganisationEnterpriseType_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("OrganisationId") ON DELETE CASCADE
);

CREATE TABLE "Person" (
    "PersonId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "PartyId" integer NOT NULL,
    "Title" integer NOT NULL,
    "FirstName" text NULL,
    "LastName" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_Person" PRIMARY KEY ("PersonId"),
    CONSTRAINT "FK_Person_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("OrganisationId") ON DELETE CASCADE,
    CONSTRAINT "FK_Person_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("PartyId") ON DELETE CASCADE
);

CREATE TABLE "ProcurementGroup" (
    "ProcurementGroupId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ProcurementGroup" PRIMARY KEY ("ProcurementGroupId"),
    CONSTRAINT "FK_ProcurementGroup_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("OrganisationId") ON DELETE CASCADE
);

CREATE TABLE "TradingOrganisation" (
    "TradingOrganisationId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "TradingName" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_TradingOrganisation" PRIMARY KEY ("TradingOrganisationId"),
    CONSTRAINT "FK_TradingOrganisation_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("OrganisationId") ON DELETE CASCADE
);

CREATE TABLE "UserGroup" (
    "UserGroupId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "UserGroupName" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserGroup" PRIMARY KEY ("UserGroupId"),
    CONSTRAINT "FK_UserGroup_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("OrganisationId") ON DELETE CASCADE
);

CREATE TABLE "UserSetting" (
    "UserSettingId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "UserSettingTypeId" integer NOT NULL,
    "UserSettingValue" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserSetting" PRIMARY KEY ("UserSettingId"),
    CONSTRAINT "FK_UserSetting_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSetting_UserSettingType_UserSettingTypeId" FOREIGN KEY ("UserSettingTypeId") REFERENCES "UserSettingType" ("UserSettingTypeId") ON DELETE CASCADE
);

CREATE TABLE "PhysicalAddress" (
    "PhysicalAddressId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "StreetAddress" text NOT NULL,
    "Locality" text NOT NULL,
    "Region" text NOT NULL,
    "PostalCode" text NOT NULL,
    "CountryCode" text NOT NULL,
    "Uprn" text NULL,
    "ContactDetailId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_PhysicalAddress" PRIMARY KEY ("PhysicalAddressId"),
    CONSTRAINT "FK_PhysicalAddress_ContactDetail_ContactDetailId" FOREIGN KEY ("ContactDetailId") REFERENCES "ContactDetail" ("ContactDetailId") ON DELETE CASCADE
);

CREATE TABLE "VirtualAddress" (
    "VirtualAddressId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VirtualAddressValue" text NULL,
    "VirtualAddressTypeId" integer NOT NULL,
    "ContactDetailId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_VirtualAddress" PRIMARY KEY ("VirtualAddressId"),
    CONSTRAINT "FK_VirtualAddress_ContactDetail_ContactDetailId" FOREIGN KEY ("ContactDetailId") REFERENCES "ContactDetail" ("ContactDetailId") ON DELETE CASCADE,
    CONSTRAINT "FK_VirtualAddress_VirtualAddressType_VirtualAddressTypeId" FOREIGN KEY ("VirtualAddressTypeId") REFERENCES "VirtualAddressType" ("VirtualAddressTypeId") ON DELETE CASCADE
);

CREATE TABLE "UserAccessRole" (
    "UserAccessRoleId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CcsAccessRoleId" integer NOT NULL,
    "OrganisationAccessRoleId" integer NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserAccessRole" PRIMARY KEY ("UserAccessRoleId"),
    CONSTRAINT "FK_UserAccessRole_CcsAccessRole_CcsAccessRoleId" FOREIGN KEY ("CcsAccessRoleId") REFERENCES "CcsAccessRole" ("CcsAccessRoleId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserAccessRole_OrganisationAccessRole_OrganisationAccessRol~" FOREIGN KEY ("OrganisationAccessRoleId") REFERENCES "OrganisationAccessRole" ("OrganisationAccessRoleId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserAccessRole_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "UserGroupMembership" (
    "UserGroupMembershipId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserGroupId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "MembershipStartDate" timestamp without time zone NOT NULL,
    "MembershipEndDate" timestamp without time zone NOT NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserGroupMembership" PRIMARY KEY ("UserGroupMembershipId"),
    CONSTRAINT "FK_UserGroupMembership_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserGroupMembership_UserGroup_UserGroupId" FOREIGN KEY ("UserGroupId") REFERENCES "UserGroup" ("UserGroupId") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_ContactDetail_ContactPointId" ON "ContactDetail" ("ContactPointId");

CREATE INDEX "IX_ContactPoint_PartyId" ON "ContactPoint" ("PartyId");

CREATE UNIQUE INDEX "IX_Organisation_PartyId" ON "Organisation" ("PartyId");

CREATE INDEX "IX_OrganisationAccessRole_OrganisationId" ON "OrganisationAccessRole" ("OrganisationId");

CREATE INDEX "IX_OrganisationEnterpriseType_EnterpriseTypeId" ON "OrganisationEnterpriseType" ("EnterpriseTypeId");

CREATE INDEX "IX_OrganisationEnterpriseType_OrganisationId" ON "OrganisationEnterpriseType" ("OrganisationId");

CREATE INDEX "IX_Party_PartyTypeId" ON "Party" ("PartyTypeId");

CREATE INDEX "IX_Person_OrganisationId" ON "Person" ("OrganisationId");

CREATE UNIQUE INDEX "IX_Person_PartyId" ON "Person" ("PartyId");

CREATE UNIQUE INDEX "IX_PhysicalAddress_ContactDetailId" ON "PhysicalAddress" ("ContactDetailId");

CREATE INDEX "IX_ProcurementGroup_OrganisationId" ON "ProcurementGroup" ("OrganisationId");

CREATE INDEX "IX_TradingOrganisation_OrganisationId" ON "TradingOrganisation" ("OrganisationId");

CREATE INDEX "IX_User_IdentityProviderIdpId" ON "User" ("IdentityProviderIdpId");

CREATE UNIQUE INDEX "IX_User_PartyId" ON "User" ("PartyId");

CREATE INDEX "IX_UserAccessRole_CcsAccessRoleId" ON "UserAccessRole" ("CcsAccessRoleId");

CREATE INDEX "IX_UserAccessRole_OrganisationAccessRoleId" ON "UserAccessRole" ("OrganisationAccessRoleId");

CREATE INDEX "IX_UserAccessRole_UserId" ON "UserAccessRole" ("UserId");

CREATE INDEX "IX_UserGroup_OrganisationId" ON "UserGroup" ("OrganisationId");

CREATE INDEX "IX_UserGroupMembership_UserGroupId" ON "UserGroupMembership" ("UserGroupId");

CREATE INDEX "IX_UserGroupMembership_UserId" ON "UserGroupMembership" ("UserId");

CREATE INDEX "IX_UserSetting_UserId" ON "UserSetting" ("UserId");

CREATE INDEX "IX_UserSetting_UserSettingTypeId" ON "UserSetting" ("UserSettingTypeId");

CREATE INDEX "IX_VirtualAddress_ContactDetailId" ON "VirtualAddress" ("ContactDetailId");

CREATE INDEX "IX_VirtualAddress_VirtualAddressTypeId" ON "VirtualAddress" ("VirtualAddressTypeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210119142331_InitialMigration', '5.0.2');

COMMIT;

