-- This genrated script has be altered to support the introduced foreign key with a data insert to "ContactPointReason" table

START TRANSACTION;

CREATE TABLE "ContactPointReason" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "CreatedPartyId" integer NOT NULL,
    "LastUpdatedPartyId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ContactPointReason" PRIMARY KEY ("Id")
);

COMMIT;

START TRANSACTION;
INSERT INTO public."ContactPointReason"("Name", "Description", "CreatedPartyId", "LastUpdatedPartyId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted")
	VALUES ('OTHER','Other reason', 0, 0, now(), now(), false);
COMMIT;

START TRANSACTION;
ALTER TABLE "ContactPoint" ADD "ContactPointReasonId" integer NOT NULL DEFAULT 1;

CREATE INDEX "IX_ContactPoint_ContactPointReasonId" ON "ContactPoint" ("ContactPointReasonId");

ALTER TABLE "ContactPoint" ADD CONSTRAINT "FK_ContactPoint_ContactPointReason_ContactPointReasonId" FOREIGN KEY ("ContactPointReasonId") REFERENCES "ContactPointReason" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210202062318_AddContactPointReason', '5.0.2');

COMMIT;

